local A = Soundstone
local passed = 0
local function eq(actual, expected, text)
    assert(actual == expected, (text or '') .. ': expected ' .. tostring(expected) .. ', got ' .. tostring(actual))
end
local function test(name, fn)
    fn(); passed=passed+1; print('PASS '..name)
end
local function cvar(name) return tonumber(Mock.cvars[name]) end

test('login initializes once without overwriting any audio settings', function()
    A.events:Fire('OnEvent','ADDON_LOADED','Soundstone')
    eq(A.initialized,nil)
    A.events:Fire('OnEvent','PLAYER_LOGIN')
    eq(A.initialized,true)
    eq(#Mock.writes,0)
    eq(A.db.schema,2);eq(A.db.positions,nil)
    eq(A.db.position.x,-23);eq(A.db.position.y,-62)
    local count=#Mock.objects
    A.events:Fire('OnEvent','PLAYER_LOGIN')
    eq(#Mock.objects,count)
end)
test('bar, panel and minimap load with persisted channel percentages', function()
    eq(A.UI.bar:IsShown(),true); eq(A.UI.panel:IsShown(),false); eq(A.UI.minimap:IsShown(),true)
    eq(A.UI.rows.master.value.textValue,'80 %'); eq(A.UI.rows.sfx.value.textValue,'60 %')
    eq(A.UI.rows.music.value.textValue,'25 %')
    eq(SLASH_SOUNDSTONE1,'/soundstone'); eq(SLASH_SOUNDSTONE2,'/azeraudio')
end)
test('music mute preserves volume and other channels', function()
    A:Toggle('music'); eq(cvar('Sound_EnableMusic'),0); eq(cvar('Sound_MusicVolume'),0.25)
    eq(cvar('Sound_SFXVolume'),0.6); eq(cvar('Sound_EnableAllSound'),1)
    eq(A.UI.rows.music.value.textValue,'25 %'); eq(A.UI.rows.music.icon.slash:IsShown(),true)
    A:Toggle('music'); eq(cvar('Sound_EnableMusic'),1)
end)
test('master toggle preserves individual mute choices and volume ratios', function()
    A:Toggle('music'); A:Toggle('master')
    eq(A.audio:Get('sfx').reason,'MASTER_OFF')
    eq(A.UI.rows.sfx.icon.slash:IsShown(),true)
    A:Toggle('master'); eq(cvar('Sound_EnableMusic'),0); eq(cvar('Sound_SFXVolume'),0.6)
    A:SetVolume('master',50); eq(cvar('Sound_MasterVolume'),0.5)
    eq(cvar('Sound_MusicVolume'),0.25); eq(cvar('Sound_SFXVolume'),0.6)
end)
test('slider changes stay muted and do not enable master', function()
    A:Toggle('master')
    A.UI.rows.music.slider:SetValue(37)
    eq(cvar('Sound_MusicVolume'),0.37); eq(cvar('Sound_EnableMusic'),0); eq(cvar('Sound_EnableAllSound'),0)
    eq(A.UI.rows.music.value.textValue,'37 %')
    A:Toggle('master')
end)
test('bounds, rounding, zero and invalid numbers', function()
    A:SetVolume('sfx',-3); eq(cvar('Sound_SFXVolume'),0); eq(cvar('Sound_EnableSFX'),1)
    eq(A.audio:Get('sfx').reason,'ZERO')
    A:SetVolume('sfx',103); eq(cvar('Sound_SFXVolume'),1)
    A:SetVolume('sfx',42.7); eq(cvar('Sound_SFXVolume'),0.43)
    local before=#Mock.writes
    eq(A.audio:SetVolume('sfx',0/0),false); eq(A.audio:SetVolume('sfx',math.huge),false)
    eq(A.audio:SetVolume('sfx','invalid'),false); eq(#Mock.writes,before)
end)
test('mouse wheel 5% and shift wheel 1%', function()
    A:SetVolume('sfx',50)
    A.UI.barControls.sfx:Fire('OnMouseWheel',1); eq(cvar('Sound_SFXVolume'),0.55)
    Mock.shift=true; A.UI.barControls.sfx:Fire('OnMouseWheel',-1); eq(cvar('Sound_SFXVolume'),0.54); Mock.shift=false
end)
test('external CVar changes refresh widgets without extra writes', function()
    local before=#Mock.writes
    Mock.cvars.Sound_MusicVolume='0.125'; Mock.cvars.Sound_EnableMusic='1'
    A.events:Fire('OnEvent','CVAR_UPDATE','Sound_MusicVolume')
    eq(A.UI.rows.music.value.textValue,'13 %'); eq(A.UI.rows.music.icon.slash:IsShown(),false)
    eq(#Mock.writes,before); eq(cvar('Sound_MusicVolume'),0.125)
end)
test('unavailable or locked CVars fail safely and revert displayed slider', function()
    local old=Mock.cvars.Sound_SFXVolume; Mock.cvars.Sound_SFXVolume=nil; A.UI:Refresh()
    eq(A.UI.rows.sfx.value.textValue,'-- %'); eq(A.audio:SetVolume('sfx',50),false)
    Mock.cvars.Sound_SFXVolume=old
    Mock.rejectWrite=true; eq(A.audio:SetVolume('sfx',70),false); eq(cvar('Sound_SFXVolume'),tonumber(old)); Mock.rejectWrite=false
    Mock.ignoreWrite=true; eq(A.audio:SetVolume('sfx',70),false); Mock.ignoreWrite=false
    Mock.throwWrite=true; eq(A.audio:SetVolume('sfx',70),false); Mock.throwWrite=false
    Mock.throwRead=true; eq(A.audio:Get('sfx').available,false); Mock.throwRead=false
    A.UI:Refresh()
end)
test('all public commands and panel opening', function()
    A:Command(''); eq(A.UI.panel:IsShown(),true)
    A:Command(''); eq(A.UI.panel:IsShown(),false)
    A:Command('  music 20  '); eq(cvar('Sound_MusicVolume'),0.2)
    A:Command('music off'); eq(cvar('Sound_EnableMusic'),0)
    A:Command('music on'); eq(cvar('Sound_EnableMusic'),1)
    A:Command('bar'); eq(A.UI.bar:IsShown(),false)
    A:Command('minimap'); eq(A.UI.minimap:IsShown(),false)
    A:Command('lock'); eq(A.db.locked,true)
    A:Command('reset'); eq(A.db.minimapAngle,225)
    A:Command('help'); A:Command('badcommand'); A:Command('music banana')
    A:Command('bar'); A:Command('minimap')
end)
test('minimap click, wheel and position changes', function()
    A.UI.minimap:Fire('OnClick','LeftButton'); eq(A.UI.panel:IsShown(),true)
    A.UI.minimap:Fire('OnClick','RightButton'); eq(A.UI.bar:IsShown(),false)
    A.db.locked=false; A.UI.minimap:Fire('OnDragStart'); eq(type(A.UI.minimap:GetScript('OnUpdate')),'function')
    A.UI.minimap:Fire('OnUpdate'); A.UI.minimap:Fire('OnDragStop'); eq(A.UI.minimap:GetScript('OnUpdate'),nil)
    Mock.time=Mock.time+1; A.UI.minimap:Fire('OnClick','LeftButton'); eq(A.UI.panel:IsShown(),true)
    A.UI.minimap:Fire('OnClick','LeftButton'); eq(A.UI.panel:IsShown(),false)
    Mock.minimapShape='SQUARE'; A.UI:PositionMinimap(); Mock.minimapShape='ROUND'
end)
test('no continuous update loop when idle', function()
    for _,o in ipairs(Mock.objects) do eq(o:GetScript('OnUpdate'),nil,'idle OnUpdate') end
end)
test('successful write returns no error and ambience/dialogue stay untouched', function()
    local ok,err=A.audio:SetVolume('music',30); eq(ok,true); eq(err,nil)
    eq(cvar('Sound_AmbienceVolume'),0.45); eq(cvar('Sound_DialogVolume'),0.9)
end)
return passed
